#!/bin/sh

if [ $1 -eq 1 ]
	then
		java -cp .:bcprov-jdk15on-154.jar RunClient $2
fi

if [ $1 -eq 2 ]
	then
		java -cp .:bcprov-jdk15on-154.jar RunFileServer $2
fi

if [ $1 -eq 3 ]
	then
		java -cp .:bcprov-jdk15on-154.jar RunGroupServer $2
fi